services:
  eureka:
    build: eureka-server
    mem_limit: 512m

  gateway:
    build: gateway-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  datetime-composite:
    build: datetime-composite-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  datetime:
    build: datetime-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 3
