server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

spring.cloud.stream:
  bindings:
    message-out-0:
      binder: local_rabbit
      contentType: application/json
      destination: queue.messages
      producer:
        routingKeyExpression: headers['routingKey']
        #partition-key-expression: headers['partitionKey']
        #partition-count: 3
  binders:
    local_rabbit:
      type: rabbit
      environment:
        spring:
          rabbitmq:
            host: 127.0.0.1
            port: 5672
            username: guest
            password: guest

---
spring.config.activate.on-profile: docker
spring.cloud.stream:
  binders:
    local_rabbit:
      environment:
        spring:
          rabbitmq:
            host: lavinmq