global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'proxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['proxy-service:8080']

  - job_name: 'math-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['math-service-1:8080']

  - job_name: 'math-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'math-service-2:8080' ]

  - job_name: 'math-3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'math-service-3:8080' ]