server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
        message-out-0:
          binder: local_kafka
          contentType: application/json
          destination: topic.messages
      binders:
        local_kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092

---
spring.config.activate.on-profile: docker

spring:
  cloud:
    stream:
      binders:
        local_kafka:
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: kafka:9092