server.port: 7002

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=order
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init.mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

app:
  product-service:
    host: localhost
    port: 7001

---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  product-service:
    host: product-service
    port: 8080