server.port: 9001

management:
  health:
    rabbit:
      enabled: false

spring.cloud.stream:
  function:
    definition: accountProcessor
  bindings:
    accountProcessor-in-0:
      destination: app.events
      contentType: application/json
      binder: local_rabbit
    accountProcessor-out-0:
      destination: app.events
      contentType: application/json
      binder: local_rabbit
  rabbit:
    bindings:
      accountProcessor-out-0:
        producer:
          routingKeyExpression: headers['routingKey']
      accountProcessor-in-0:
        consumer:
          binding-routing-key:
  binders:
    local_rabbit:
      type: rabbit
      environment:
        spring:
          rabbitmq:
            host: 127.0.0.1
            port: 5672
            username: guest
            password: guest

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=order
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init.mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

---
spring.config.activate.on-profile: docker

spring.cloud.stream:
  binders:
    local_rabbit:
      environment:
        spring:
          rabbitmq:
            host: lavinmq