services:
  publisher:
    build: publisher-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mosquitto:
        condition: service_healthy

  subscriber:
    build: subscriber-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mosquitto:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"     # MQTT broker port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 mosquitto_sub -h localhost -t healthcheck -C 1 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 60
