server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

spring.cloud.stream:
  function:
    definition: processPrimes
  bindings:
    processPrimes-in-0:
      group: messagesGroup
      binder: local_rabbit
      contentType: application/json
      destination: queue.messages
      consumer:
        binding-routing-key: 'math.#'
    processPrimes-out-0:
      binder: local_rabbit
      contentType: application/json
      destination: notification.messages
  binders:
    local_rabbit:
      type: rabbit
      environment:
        spring:
          rabbitmq:
            host: 127.0.0.1
            port: 5672
            username: guest
            password: guest

---
spring.config.activate.on-profile: docker

server:
  port: 8080

spring.cloud.stream:
  binders:
    local_rabbit:
      environment:
        spring:
          rabbitmq:
            host: lavinmq